Sabina: /home/patrick/projects/Gesture_Therapy_Linux/src/Joystick_Reader/Joypad.h File Reference
Joypad.h File Reference
This file provides a generic cross platform joypad interface for Win32 & Linux. Generally the linux implimentation is not as cool as using DirectX, you only really get hold of the values. Using force feedback is beyond Linux at the moment. Oh well...
#include <string>
#include <iostream>
Classes
struct XInputJoypad
class CJoypad
Typedefs
typedef long LONG
make sure DWORD and LONG and defined in linux land
typedef unsigned long DWORD
Functions
unsigned int NumJoypads ()
This function returns the number of working joypads attached to the computer.
XInputJoypad * GetJoypad (const unsigned int=0)
This function returns a pointer to the requested Joypad or NULL if no joypad is available.
void FreeInput ()
This function is called to destroy the input at the end of the game.
bool InitInput ()
This function can be used to initialise the joypad lib.
bool UpdateInputState ()
You should call this to update the state of the joypad.
Detailed Description
This file provides a generic cross platform joypad interface for Win32 & Linux. Generally the linux implimentation is not as cool as using DirectX, you only really get hold of the values. Using force feedback is beyond Linux at the moment. Oh well...
Author
Rob Bateman
Date
12-jan-2004
Definition in file Joypad.h.
Function Documentation
FreeInput()
void FreeInput ()
This function is called to destroy the input at the end of the game.
Cleans up Direct Input.
This function is called to destroy the input at the end of the game.
Definition at line 405 of file Joypad.cpp.
Referenced by CJoypad::POV().
 {
     std::vector< XInputJoypad* >::iterator it = g_aJoypads.begin();
     for( ; it != g_aJoypads.end(); ++it )
     {
         delete (*it);
     }
     g_aJoypads.resize(0);
 }
InitInput()
bool InitInput ()
This function can be used to initialise the joypad lib.
Initialize the DirectInput variables.
Returns
true if OK, false if it fails
This function can be used to initialise the joypad lib.
Returns
true if OK
Definition at line 383 of file Joypad.cpp.
Referenced by CJoypad::POV().
 {
     bool ret=false;
     int fd;
     if ( (fd = open("/dev/input/js0", O_RDONLY)) > 0 )
     {
         CJoypad* ptr = new CJoypad;
         ioctl(fd, JSIOCGVERSION, &ptr->version);
         ioctl(fd, JSIOCGAXES, &ptr->m_iAxes);
         ioctl(fd, JSIOCGBUTTONS, &ptr->m_nButtons);
         ioctl(fd, JSIOCGNAME(NAME_LENGTH), ptr->name);
         fcntl(fd, F_SETFL, O_NONBLOCK);
         ptr->fd = fd;
         g_aJoypads.push_back(ptr);
         ret=true;
     }
     return ret;
 }
UpdateInputState()
bool UpdateInputState ()
You should call this to update the state of the joypad.
Returns
true if OK.
Definition at line 370 of file Joypad.cpp.
Referenced by CJoypad::POV().
 {
     std::vector< XInputJoypad* >::iterator it = g_aJoypads.begin();
     for( ; it != g_aJoypads.end(); ++it )
     {
         (*it)->Update();
     }
 }