Sabina: TUIO::TuioContainer Class Reference
TUIO::TuioContainer Class Reference
#include <TuioContainer.h>
Public Member Functions
TuioContainer (TuioTime ttime, long si, float xp, float yp)
TuioContainer (long si, float xp, float yp)
TuioContainer (TuioContainer *tcon)
virtual ~TuioContainer ()
virtual void update (TuioTime ttime, float xp, float yp)
virtual void stop (TuioTime ttime)
virtual void update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma)
virtual void update (float xp, float yp, float xs, float ys, float ma)
virtual void update (TuioContainer *tcon)
virtual void remove (TuioTime ttime)
virtual long getSessionID ()
virtual float getXSpeed ()
virtual float getYSpeed ()
virtual TuioPoint getPosition ()
virtual std::list< TuioPoint > getPath ()
virtual float getMotionSpeed ()
virtual float getMotionAccel ()
virtual int getTuioState ()
virtual bool isMoving ()
Public Member Functions inherited from TUIO::TuioPoint
TuioPoint (float xp, float yp)
TuioPoint (TuioTime ttime, float xp, float yp)
TuioPoint (TuioPoint *tpoint)
~TuioPoint ()
void update (TuioPoint *tpoint)
void update (float xp, float yp)
void update (TuioTime ttime, float xp, float yp)
float getX ()
float getY ()
float getDistance (float xp, float yp)
float getDistance (TuioPoint *tpoint)
float getAngle (float xp, float yp)
float getAngle (TuioPoint *tpoint)
float getAngleDegrees (float xp, float yp)
float getAngleDegrees (TuioPoint *tpoint)
int getScreenX (int width)
int getScreenY (int height)
TuioTime getTuioTime ()
TuioTime getStartTime ()
Protected Attributes
long session_id
float x_speed
float y_speed
float motion_speed
float motion_accel
std::list< TuioPoint > path
int state
Protected Attributes inherited from TUIO::TuioPoint
float xpos
float ypos
TuioTime currentTime
TuioTime startTime
Detailed Description
The abstract TuioContainer class defines common attributes that apply to both subclasses TuioObject and TuioCursor.
Author
Martin Kaltenbrunner
Version
1.4
Definition at line 44 of file TuioContainer.h.
Constructor & Destructor Documentation
TuioContainer() [1/3]
TUIO::TuioContainer::TuioContainer (TuioTime ttime, long si, float xp, float yp) inline
This constructor takes a TuioTime argument and assigns it along with the provided Session ID, X and Y coordinate to the newly created TuioContainer.
Parameters
ttime the TuioTime to assign
si the Session ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 86 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime, TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
                                                                    :TuioPoint(ttime, xp,yp) {
             session_id = si;
             x_speed = 0.0f;
             y_speed = 0.0f;
             motion_speed = 0.0f;
             motion_accel = 0.0f;
             TuioPoint p(currentTime,xpos,ypos);
             path.push_back(p);
             state = TUIO_ADDED;
         };
TuioContainer() [2/3]
TUIO::TuioContainer::TuioContainer (long si, float xp, float yp) inline
This constructor takes the provided Session ID, X and Y coordinate and assigs these values to the newly created TuioContainer.
Parameters
si the Session ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 106 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime, TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
                                                    :TuioPoint(xp,yp) {
             session_id = si;
             x_speed = 0.0f;
             y_speed = 0.0f;
             motion_speed = 0.0f;
             motion_accel = 0.0f;
             TuioPoint p(currentTime,xpos,ypos);
             path.push_back(p);
             state = TUIO_ADDED;
         };
TuioContainer() [3/3]
TUIO::TuioContainer::TuioContainer (TuioContainer * tcon) inline
This constructor takes the atttibutes of the provided TuioContainer and assigs these values to the newly created TuioContainer.
Parameters
tcon the TuioContainer to assign
Definition at line 124 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime, getSessionID(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
                                            :TuioPoint(tcon) {
             session_id = tcon->getSessionID();
             x_speed = 0.0f;
             y_speed = 0.0f;
             motion_speed = 0.0f;
             motion_accel = 0.0f;
             TuioPoint p(currentTime,xpos,ypos);
             path.push_back(p);
             state = TUIO_ADDED;
         };
~TuioContainer()
virtual TUIO::TuioContainer::~TuioContainer () inline virtual
The destructor is doing nothing in particular.
Definition at line 139 of file TuioContainer.h.
 {};
Member Function Documentation
getMotionAccel()
virtual float TUIO::TuioContainer::getMotionAccel () inline virtual
Returns the motion acceleration of this TuioContainer.
Returns
the motion acceleration of this TuioContainer
Definition at line 322 of file TuioContainer.h.
References motion_accel.
Referenced by update(), TuioDump::updateTuioCursor(), and TuioDump::updateTuioObject().
{
             return motion_accel;
         };
getMotionSpeed()
virtual float TUIO::TuioContainer::getMotionSpeed () inline virtual
Returns the motion speed of this TuioContainer.
Returns
the motion speed of this TuioContainer
Definition at line 314 of file TuioContainer.h.
References motion_speed.
Referenced by update(), TuioDump::updateTuioCursor(), and TuioDump::updateTuioObject().
{
             return motion_speed;
         };
getPath()
virtual std::list<TuioPoint> TUIO::TuioContainer::getPath () inline virtual
Returns the path of this TuioContainer.
Returns
the path of this TuioContainer
Definition at line 306 of file TuioContainer.h.
References path.
{
             return path;
         };
getPosition()
virtual TuioPoint TUIO::TuioContainer::getPosition () inline virtual
Returns the position of this TuioContainer.
Returns
the position of this TuioContainer
Definition at line 297 of file TuioContainer.h.
References TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
{
             TuioPoint p(xpos,ypos);
             return p;
         };
getSessionID()
virtual long TUIO::TuioContainer::getSessionID () inline virtual
Returns the Session ID of this TuioContainer.
Returns
the Session ID of this TuioContainer
Definition at line 273 of file TuioContainer.h.
References session_id.
Referenced by TuioDump::addTuioCursor(), TuioDump::addTuioObject(), TuioDump::removeTuioCursor(), TuioDump::removeTuioObject(), TuioContainer(), TuioDump::updateTuioCursor(), and TuioDump::updateTuioObject().
{
             return session_id;
         };
getTuioState()
virtual int TUIO::TuioContainer::getTuioState () inline virtual
Returns the TUIO state of this TuioContainer.
Returns
the TUIO state of this TuioContainer
Definition at line 330 of file TuioContainer.h.
References state.
{
             return state;
         };
getXSpeed()
virtual float TUIO::TuioContainer::getXSpeed () inline virtual
Returns the X velocity of this TuioContainer.
Returns
the X velocity of this TuioContainer
Definition at line 281 of file TuioContainer.h.
References x_speed.
Referenced by update().
{
             return x_speed;
         };
getYSpeed()
virtual float TUIO::TuioContainer::getYSpeed () inline virtual
Returns the Y velocity of this TuioContainer.
Returns
the Y velocity of this TuioContainer
Definition at line 289 of file TuioContainer.h.
References y_speed.
Referenced by update().
{
             return y_speed;
         };
isMoving()
virtual bool TUIO::TuioContainer::isMoving () inline virtual
Returns true of this TuioContainer is moving.
Returns
true of this TuioContainer is moving
Reimplemented in TUIO::TuioObject.
Definition at line 338 of file TuioContainer.h.
{
             if ((state==TUIO_ACCELERATING) || (state==TUIO_DECELERATING)) return true;
             else return false;
         };
remove()
virtual void TUIO::TuioContainer::remove (TuioTime ttime) inline virtual
Assigns the REMOVE state to this TuioContainer and sets its TuioTime time stamp to the provided TuioTime argument.
Parameters
ttime the TuioTime to assign
Definition at line 264 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime.
{
             currentTime = ttime;
             state = TUIO_REMOVED;
         }
stop()
virtual void TUIO::TuioContainer::stop (TuioTime ttime) inline virtual
This method is used to calculate the speed and acceleration values of TuioContainers with unchanged positions.
Reimplemented in TUIO::TuioObject.
Definition at line 179 of file TuioContainer.h.
References update(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
{
             update(ttime,xpos,ypos);
         };
update() [1/4]
virtual void TUIO::TuioContainer::update (TuioTime ttime, float xp, float yp) inline virtual
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate to the private TuioContainer attributes. The speed and accleration values are calculated accordingly.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 150 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime, TUIO::TuioTime::getTotalMilliseconds(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioPoint::getX(), TUIO::TuioPoint::getY(), motion_speed, TUIO::TuioPoint::update(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
Referenced by stop(), and TUIO::TuioObject::update().
{
             TuioPoint lastPoint = path.back();
             TuioPoint::update(ttime,xp, yp);
             TuioTime diffTime = currentTime - lastPoint.getTuioTime();
             float dt = diffTime.getTotalMilliseconds()/1000.0f;
             float dx = xpos - lastPoint.getX();
             float dy = ypos - lastPoint.getY();
             float dist = sqrt(dx*dx+dy*dy);
             float last_motion_speed = motion_speed;
             x_speed = dx/dt;
             y_speed = dy/dt;
             motion_speed = dist/dt;
             motion_accel = (motion_speed - last_motion_speed)/dt;
             TuioPoint p(currentTime,xpos,ypos);
             path.push_back(p);
             if (motion_accel>0) state = TUIO_ACCELERATING;
             else if (motion_accel<0) state = TUIO_DECELERATING;
             else state = TUIO_STOPPED;
         };
update() [2/4]
virtual void TUIO::TuioContainer::update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma) inline virtual
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate, X and Y velocity and acceleration to the private TuioContainer attributes.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
ma the acceleration to assign
Definition at line 195 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime, TUIO::TuioPoint::update(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
{
             TuioPoint::update(ttime,xp, yp);
             x_speed = xs;
             y_speed = ys;
             motion_speed = (float)sqrt(x_speed*x_speed+y_speed*y_speed);
             motion_accel = ma;
             TuioPoint p(currentTime,xpos,ypos);
             path.push_back(p);
             if (motion_accel>0) state = TUIO_ACCELERATING;
             else if (motion_accel<0) state = TUIO_DECELERATING;
             else state = TUIO_STOPPED;
         };
update() [3/4]
virtual void TUIO::TuioContainer::update (float xp, float yp, float xs, float ys, float ma) inline virtual
Assigns the provided X and Y coordinate, X and Y velocity and acceleration to the private TuioContainer attributes. The TuioTime time stamp remains unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
ma the acceleration to assign
Definition at line 220 of file TuioContainer.h.
References TUIO::TuioPoint::currentTime, TUIO::TuioPoint::update(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
{
             TuioPoint::update(xp,yp);
             x_speed = xs;
             y_speed = ys;
             motion_speed = (float)sqrt(x_speed*x_speed+y_speed*y_speed);
             motion_accel = ma;
             path.pop_back();
             TuioPoint p(currentTime,xpos,ypos);
             path.push_back(p);
             if (motion_accel>0) state = TUIO_ACCELERATING;
             else if (motion_accel<0) state = TUIO_DECELERATING;
             else state = TUIO_STOPPED;
         };
update() [4/4]
virtual void TUIO::TuioContainer::update (TuioContainer * tcon) inline virtual
Takes the atttibutes of the provided TuioContainer and assigs these values to this TuioContainer. The TuioTime time stamp of this TuioContainer remains unchanged.
Parameters
tcon the TuioContainer to assign
Definition at line 243 of file TuioContainer.h.
References getMotionAccel(), getMotionSpeed(), TUIO::TuioPoint::getTuioTime(), getXSpeed(), getYSpeed(), TUIO::TuioPoint::update(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
{
             TuioPoint::update(tcon);
             x_speed = tcon->getXSpeed();
             y_speed =  tcon->getYSpeed();
             motion_speed =  tcon->getMotionSpeed();
             motion_accel = tcon->getMotionAccel();
             TuioPoint p(tcon->getTuioTime(),xpos,ypos);
             path.push_back(p);
             if (motion_accel>0) state = TUIO_ACCELERATING;
             else if (motion_accel<0) state = TUIO_DECELERATING;
             else state = TUIO_STOPPED;
         };
Member Data Documentation
motion_accel
float TUIO::TuioContainer::motion_accel protected
The motion acceleration value.
Definition at line 66 of file TuioContainer.h.
Referenced by getMotionAccel().
motion_speed
float TUIO::TuioContainer::motion_speed protected
The motion speed value.
Definition at line 62 of file TuioContainer.h.
Referenced by getMotionSpeed(), and update().
path
std::list<TuioPoint> TUIO::TuioContainer::path protected
A List of TuioPoints containing all the previous positions of the TUIO component.
Definition at line 70 of file TuioContainer.h.
Referenced by getPath(), and TUIO::TuioObject::update().
session_id
long TUIO::TuioContainer::session_id protected
The unique session ID number that is assigned to each TUIO object or cursor.
Definition at line 50 of file TuioContainer.h.
Referenced by getSessionID().
state
int TUIO::TuioContainer::state protected
Reflects the current state of the TuioComponent
Definition at line 74 of file TuioContainer.h.
Referenced by getTuioState(), TUIO::TuioObject::isMoving(), and TUIO::TuioObject::update().
x_speed
float TUIO::TuioContainer::x_speed protected
The X-axis velocity value.
Definition at line 54 of file TuioContainer.h.
Referenced by getXSpeed().
y_speed
float TUIO::TuioContainer::y_speed protected
The Y-axis velocity value.
Definition at line 58 of file TuioContainer.h.
Referenced by getYSpeed().
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioContainer.h