Sabina: TUIO::TuioClient Class Reference
TUIO::TuioClient Class Reference
#include <TuioClient.h>
Public Member Functions
TuioClient (int port=3333)
~TuioClient ()
void connect (bool lock=false)
void disconnect ()
bool isConnected ()
void addTuioListener (TuioListener *listener)
void removeTuioListener (TuioListener *listener)
void removeAllTuioListeners ()
std::list< TuioObject * > getTuioObjects ()
std::list< TuioCursor * > getTuioCursors ()
TuioObject * getTuioObject (long s_id)
TuioCursor * getTuioCursor (long s_id)
void lockObjectList ()
void unlockObjectList ()
void lockCursorList ()
void unlockCursorList ()
void ProcessPacket (const char *data, int size, const IpEndpointName &remoteEndpoint)
Public Attributes
UdpListeningReceiveSocket * socket
Protected Member Functions
void ProcessBundle (const osc::ReceivedBundle &b, const IpEndpointName &remoteEndpoint)
void ProcessMessage (const osc::ReceivedMessage &message, const IpEndpointName &remoteEndpoint)
Detailed Description
The TuioClient class is the central TUIO protocol decoder component. It provides a simple callback infrastructure using the TuioListener interface. In order to receive and decode TUIO messages an instance of TuioClient needs to be created. The TuioClient instance then generates TUIO events which are broadcasted to all registered classes that implement the TuioListener interface.
TuioClient *client = new TuioClient();
client->addTuioListener(myTuioListener);
client->connect();
Author
Martin Kaltenbrunner
Version
1.4
Definition at line 62 of file TuioClient.h.
Constructor & Destructor Documentation
TuioClient()
TUIO::TuioClient::TuioClient (int port = 3333)
This constructor creates a TuioClient that listens to the provided port
Parameters
port the incoming TUIO UDP port number, defaults to 3333 if no argument is provided
~TuioClient()
TUIO::TuioClient::~TuioClient ()
The destructor is doing nothing in particular.
Member Function Documentation
addTuioListener()
void TUIO::TuioClient::addTuioListener (TuioListener * listener)
Adds the provided TuioListener to the list of registered TUIO event listeners
Parameters
listener the TuioListener to add
Referenced by isConnected(), and Tuio_Client::Main().
connect()
void TUIO::TuioClient::connect (bool lock = false)
The TuioClient starts listening to TUIO messages on the configured UDP port All received TUIO messages are decoded and the resulting TUIO events are broadcasted to all registered TuioListeners
Parameters
lock running in the background if set to false (default)
Referenced by Tuio_Client::Main().
disconnect()
void TUIO::TuioClient::disconnect ()
The TuioClient stops listening to TUIO messages on the configured UDP port
Referenced by Tuio_Client::Main().
getTuioCursor()
TuioCursor* TUIO::TuioClient::getTuioCursor (long s_id)
Returns the TuioCursor corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioCursor
Returns
an active TuioCursor corresponding to the provided Session ID or NULL
Referenced by removeAllTuioListeners().
getTuioCursors()
std::list<TuioCursor*> TUIO::TuioClient::getTuioCursors ()
Returns a List of all currently active TuioCursors
Returns
a List of all currently active TuioCursors
Referenced by removeAllTuioListeners().
getTuioObject()
TuioObject* TUIO::TuioClient::getTuioObject (long s_id)
Returns the TuioObject corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioObject
Returns
an active TuioObject corresponding to the provided Session ID or NULL
Referenced by removeAllTuioListeners().
getTuioObjects()
std::list<TuioObject*> TUIO::TuioClient::getTuioObjects ()
Returns a List of all currently active TuioObjects
Returns
a List of all currently active TuioObjects
Referenced by removeAllTuioListeners().
isConnected()
bool TUIO::TuioClient::isConnected () inline
Returns true if this TuioClient is currently connected.
Returns
true if this TuioClient is currently connected
Definition at line 94 of file TuioClient.h.
References addTuioListener(), and removeTuioListener().
 { return connected; }
lockCursorList()
void TUIO::TuioClient::lockCursorList ()
Locks the TuioCursor list in order to avoid updates during access
Referenced by removeAllTuioListeners().
lockObjectList()
void TUIO::TuioClient::lockObjectList ()
Locks the TuioObject list in order to avoid updates during access
Referenced by removeAllTuioListeners().
ProcessMessage()
void TUIO::TuioClient::ProcessMessage (const osc::ReceivedMessage & message, const IpEndpointName & remoteEndpoint) protected
The OSC callback method where all TUIO messages are received and decoded and where the TUIO event callbacks are dispatched
Parameters
message the received OSC message
remoteEndpoint the received OSC message origin
Referenced by removeAllTuioListeners().
removeAllTuioListeners()
void TUIO::TuioClient::removeAllTuioListeners () inline
Removes all TuioListener from the list of registered TUIO event listeners
Definition at line 113 of file TuioClient.h.
References getTuioCursor(), getTuioCursors(), getTuioObject(), getTuioObjects(), lockCursorList(), lockObjectList(), ProcessMessage(), unlockCursorList(), and unlockObjectList().
{
             listenerList.clear();
         }
removeTuioListener()
void TUIO::TuioClient::removeTuioListener (TuioListener * listener)
Removes the provided TuioListener from the list of registered TUIO event listeners
Parameters
listener the TuioListener to remove
Referenced by isConnected().
unlockCursorList()
void TUIO::TuioClient::unlockCursorList ()
Releases the lock of the TuioCursor list
Referenced by removeAllTuioListeners().
unlockObjectList()
void TUIO::TuioClient::unlockObjectList ()
Releases the lock of the TuioObject list
Referenced by removeAllTuioListeners().
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioClient.h