Sabina: TuioDump Class Reference
TuioDump Class Reference
Public Member Functions
void addTuioObject (TuioObject *tobj)
void updateTuioObject (TuioObject *tobj)
void removeTuioObject (TuioObject *tobj)
void addTuioCursor (TuioCursor *tcur)
void updateTuioCursor (TuioCursor *tcur)
void removeTuioCursor (TuioCursor *tcur)
void refresh (TuioTime frameTime)
Public Member Functions inherited from TUIO::TuioListener
virtual ~TuioListener ()
Detailed Description
Definition at line 40 of file TuioDump.h.
Member Function Documentation
addTuioCursor()
void TuioDump::addTuioCursor (TuioCursor * tcur) virtual
This callback method is invoked by the TuioClient when a new TuioCursor is added to the session.
Parameters
tcur the TuioCursor reference associated to the addTuioCursor event
Implements TUIO::TuioListener.
Definition at line 73 of file Main.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
{
     std::cout << "add cur " << tcur->getCursorID() << " (" <<  tcur->getSessionID() << ") " << tcur->getX() << " " << tcur->getY() << std::endl;
 }
addTuioObject()
void TuioDump::addTuioObject (TuioObject * tobj) virtual
This callback method is invoked by the TuioClient when a new TuioObject is added to the session.
Parameters
tobj the TuioObject reference associated to the addTuioObject event
Implements TUIO::TuioListener.
Definition at line 60 of file Main.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
{
     std::cout << "add obj " << tobj->getSymbolID() << " (" << tobj->getSessionID() << ") "<< tobj->getX() << " " << tobj->getY() << " " << tobj->getAngle() << std::endl;
 }
refresh()
void TuioDump::refresh (TuioTime ftime) virtual
This callback method is invoked by the TuioClient to mark the end of a received TUIO message bundle.
Parameters
ftime the TuioTime associated to the current TUIO message bundle
Implements TUIO::TuioListener.
Definition at line 86 of file Main.cpp.
{
     //std::cout << "refresh " << frameTime.getTotalMilliseconds() << std::endl;
 }
removeTuioCursor()
void TuioDump::removeTuioCursor (TuioCursor * tcur) virtual
This callback method is invoked by the TuioClient when an existing TuioCursor is removed from the session.
Parameters
tcur the TuioCursor reference associated to the removeTuioCursor event
Implements TUIO::TuioListener.
Definition at line 82 of file Main.cpp.
References TUIO::TuioCursor::getCursorID(), and TUIO::TuioContainer::getSessionID().
{
     std::cout << "del cur " << tcur->getCursorID() << " (" <<  tcur->getSessionID() << ")" << std::endl;
 }
removeTuioObject()
void TuioDump::removeTuioObject (TuioObject * tobj) virtual
This callback method is invoked by the TuioClient when an existing TuioObject is removed from the session.
Parameters
tobj the TuioObject reference associated to the removeTuioObject event
Implements TUIO::TuioListener.
Definition at line 69 of file Main.cpp.
References TUIO::TuioContainer::getSessionID(), and TUIO::TuioObject::getSymbolID().
{
     std::cout << "del obj " << tobj->getSymbolID() << " (" << tobj->getSessionID() << ")" << std::endl;
 }
updateTuioCursor()
void TuioDump::updateTuioCursor (TuioCursor * tcur) virtual
This callback method is invoked by the TuioClient when an existing TuioCursor is updated during the session.
Parameters
tcur the TuioCursor reference associated to the updateTuioCursor event
Implements TUIO::TuioListener.
Definition at line 77 of file Main.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::getMotionSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
{
     std::cout << "set cur " << tcur->getCursorID() << " (" <<  tcur->getSessionID() << ") " << tcur->getX() << " " << tcur->getY()
                 << " " << tcur->getMotionSpeed() << " " << tcur->getMotionAccel() << " " << std::endl;
 }
updateTuioObject()
void TuioDump::updateTuioObject (TuioObject * tobj) virtual
This callback method is invoked by the TuioClient when an existing TuioObject is updated during the session.
Parameters
tobj the TuioObject reference associated to the updateTuioObject event
Implements TUIO::TuioListener.
Definition at line 64 of file Main.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::getMotionSpeed(), TUIO::TuioObject::getRotationAccel(), TUIO::TuioObject::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
{
     std::cout << "set obj " << tobj->getSymbolID() << " (" << tobj->getSessionID() << ") "<< tobj->getX() << " " << tobj->getY() << " " << tobj->getAngle()
                 << " " << tobj->getMotionSpeed() << " " << tobj->getRotationSpeed() << " " << tobj->getMotionAccel() << " " << tobj->getRotationAccel() << std::endl;
 }
The documentation for this class was generated from the following files:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioDump.h
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/Main.cpp