Sabina: NetThread Class Reference
NetThread Class Reference
Public Member Functions
NetThread ()
Creates a new NetThread.
void SetOutputStream (FILE *stream=stdout)
int OpenReadPort (int port, int buffersize=1024)
Opens the port.
int OpenOutputAddress (char *address, int port, int buffersize=1024)
Opens the port.
void SetMessage (const char *s)
void Write ()
Writes a message to the port.
void Write (const char *s)
void Read ()
Reads the conection port.
char * GetIncoming ()
Reads in the message from the port.
void Close ()
Closes the conection.
void Accept ()
Accepts a conection.
int GetStatus ()
Gets the status (if status > 0 there is a message)
NetThread ()
Creates a new NetThread.
void SetOutputStream (FILE *stream=stdout)
int OpenReadPort (int port, int buffersize=1024)
Opens the port.
int OpenOutputAddress (char *address, int port, int buffersize=1024)
Opens the port.
void SetMessage (const char *s)
void Write ()
Writes a message to the port.
void Write (const char *s)
void Read ()
Reads the conection port.
char * GetIncoming ()
Reads in the message from the port.
void Close ()
Closes the conection.
void Accept ()
Accepts a conection.
int GetStatus ()
Gets the status (if status > 0 there is a message)
Public Member Functions inherited from Thread
virtual void * run ()
bool start ()
bool isRunning ()
int join ()
void exit ()
void stop ()
virtual void * run ()
bool start ()
bool isRunning ()
int join ()
void exit ()
void stop ()
void * memberFunction (void)
void startThread (void)
Public Attributes
deque< string > messages
Additional Inherited Members
Static Public Member Functions inherited from Thread
static void * callMemberFunction (void *arg)
Protected Attributes inherited from Thread
bool running
Detailed Description
Definition at line 26 of file NetThread.h.
Constructor & Destructor Documentation
NetThread() [1/2]
NetThread::NetThread ()
Creates a new NetThread.
!
Definition at line 6 of file NetThread.cpp.
 {
     buffersize = 1024;
     g_in = 0;
     g_out = 0;
     incoming = 0;
     reply = 0;
 #ifdef WIN32
     gsNetPollInit();
 #endif
 }
NetThread() [2/2]
NetThread::NetThread ()
Creates a new NetThread.
!
Member Function Documentation
Accept() [1/2]
void NetThread::Accept ()
Accepts a conection.
!
Definition at line 125 of file NetThread.cpp.
Referenced by Network_Server::Main().
 {
     gsNetPollAccept(g_in);
 }
Accept() [2/2]
void NetThread::Accept ()
Accepts a conection.
!
Close() [1/2]
void NetThread::Close ()
Closes the conection.
!
Definition at line 114 of file NetThread.cpp.
 {
     if (g_out != g_in)
     {
         gsNetPollClose(g_out);
     }
     gsNetPollClose(g_in);
     free(incoming);
     free(reply);
 }
Close() [2/2]
void NetThread::Close ()
Closes the conection.
!
GetIncoming() [1/2]
char* NetThread::GetIncoming ()
Reads in the message from the port.
!
GetIncoming() [2/2]
char * NetThread::GetIncoming ()
Reads in the message from the port.
!
Definition at line 109 of file NetThread.cpp.
Referenced by Network_Client::Main(), and Network_Server::Main().
 {
     return incoming;
 }
GetStatus() [1/2]
int NetThread::GetStatus ()
Gets the status (if status > 0 there is a message)
!
GetStatus() [2/2]
int NetThread::GetStatus ()
Gets the status (if status > 0 there is a message)
!
Definition at line 130 of file NetThread.cpp.
Referenced by Network_Client::Main(), and Network_Server::Main().
 {
     return g_in->status;
 }
OpenOutputAddress() [1/2]
int NetThread::OpenOutputAddress (char * address, int port, int buffersize = 1024)
Opens the port.
!Opens a port
Parameters
port Defines the port to open
buffersize Size of the buffer used default=1024
Definition at line 50 of file NetThread.cpp.
Referenced by Network_Client::Main().
 {
     fprintf(output, "Directing output to %s:%d\n", address, port);
     g_out = gsNetPollOpen(address, port, buffersize, "w", NULL);
     g_in=g_out;
     if (!g_out)
     {
         return 0;
     }
     else
     {
         incoming = (char *)calloc(buffersize, sizeof(char));
         reply = (char *)calloc(buffersize, sizeof(char));
         return 1;
     }
 }
OpenOutputAddress() [2/2]
int NetThread::OpenOutputAddress (char * address, int port, int buffersize = 1024)
Opens the port.
!Opens a port
Parameters
port Defines the port to open
buffersize Size of the buffer used default=1024
OpenReadPort() [1/2]
int NetThread::OpenReadPort (int port, int buffersize = 1024)
Opens the port.
!Opens a port
Parameters
port Defines the port to open
buffersize Size of the buffer used default=1024
OpenReadPort() [2/2]
int NetThread::OpenReadPort (int port, int buffersize = 1024)
Opens the port.
!Opens a port
Parameters
port Defines the port to open
buffersize Size of the buffer used default=1024
Definition at line 31 of file NetThread.cpp.
Referenced by Network_Server::Main().
 {
     const int OK = 1;
     const int FAIL = 0;
     fprintf(output, "Listening connections from port %d\n", port);
     g_in = gsNetPollOpen("localhost", port, buffersize, "r", NULL);
     assert(g_in != NULL);
     if (!g_in)
     {
         return 0;
     }
     else
     {
         incoming = (char *)calloc(buffersize, sizeof(char));
         reply = (char *)calloc(buffersize, sizeof(char));
         return 1;
     }
 }
Read() [1/2]
void NetThread::Read ()
Reads the conection port.
!
Read() [2/2]
void NetThread::Read ()
Reads the conection port.
!
Definition at line 89 of file NetThread.cpp.
Referenced by Network_Client::Main(), and Network_Server::Main().
 {
     bzero(incoming, strlen(incoming) + 1);
     strcpy(incoming, gsNetPollRead(g_in));
     if (g_in->status != -1)
     {
         if(g_in->status > 0)
         {
             incoming[g_in->status] = '\0';
             //fprintf(output, "Got message: %s\n", incoming);
             //std::stringstream ss;
             //ss  << incoming ;
             //std::string temp=ss.str();
             //std::cout <<temp << std::endl;
         }
     }
 }
Write() [1/2]
void NetThread::Write ()
Writes a message to the port.
!
Parameters
s content to write
Write() [2/2]
void NetThread::Write ()
Writes a message to the port.
!
Parameters
s content to write
Definition at line 72 of file NetThread.cpp.
Referenced by Network_Client::Main(), and Network_Server::Main().
 {
     if (!g_out)
     {
         g_out = g_in;
     }
 //     fputs("Sending reply...", output);
 //     fputs(reply, output);
     gsNetPollWrite(g_out, reply);
 }
The documentation for this class was generated from the following files:
/home/patrick/projects/Gesture_Therapy_Linux/src/Network_Client/NetThread.h
/home/patrick/projects/Gesture_Therapy_Linux/src/Network_Client/NetThread.cpp