Sabina: File_Writer Class Reference
File_Writer Class Reference
File_Writer plugin.
#include <File_Writer.h>
Public Member Functions
void Main ()
Main funcction of the plugin.
bool loadConfiguration ()
Load configuration.
bool saveConfiguration ()
Save configuration.
bool Initialize_Output ()
Initialize Output variables for the plugin to publish.
bool Initialize_Input ()
Initialize Input variables for the plugin to publish.
void run ()
Execute plugin.
void stop ()
Stop plugin.
Additional Inherited Members
Static Public Member Functions inherited from IPlugin
static void * IncWrapper (void *thisPtr)
Wrapps the Main function of the plugin object to ANSI C to be pased as a parameter to pthread_create.
Public Attributes inherited from IPlugin
pthread_t thread_id
bool running
bool stoped
Detailed Description
File_Writer plugin.
This plugin is a network server that accepts client conections to comunicate with other programs (running on the same computer or over the network)
Author
Patrick Heyer, patri.nosp@m.ckhe.nosp@m.y@pro.nosp@m.digy.nosp@m..net..nosp@m.mx, Juan Herrera juan_.nosp@m.anto.nosp@m.nio_@.nosp@m.hotm.nosp@m.ail.c.nosp@m.om, Manuel Oropeza zodia.nosp@m.cani.nosp@m.matio.nosp@m.ns@m.nosp@m.sn.co.nosp@m.m
Date
jul 04, 2012
Version
1.0
Definition at line 13 of file File_Writer.h.
Member Function Documentation
Initialize_Input()
bool File_Writer::Initialize_Input () virtual
Initialize Input variables for the plugin to publish.
Returns
bool
Implements IPlugin.
Definition at line 150 of file Main.cpp.
 {
     RShoulder_X=Shared_Memory::getInstance().Register_Double_Input("RIGHT_SHOULDER_X");
     RShoulder_Y=Shared_Memory::getInstance().Register_Double_Input("RIGHT_SHOULDER_Y");
     RShoulder_Z=Shared_Memory::getInstance().Register_Double_Input("RIGHT_SHOULDER_Z");
     RElbow_X=Shared_Memory::getInstance().Register_Double_Input("RIGHT_ELBOW_X");
     RElbow_Y=Shared_Memory::getInstance().Register_Double_Input("RIGHT_ELBOW_Y");
     RElbow_Z=Shared_Memory::getInstance().Register_Double_Input("RIGHT_ELBOW_Z");
     RHand_X=Shared_Memory::getInstance().Register_Double_Input("RIGHT_HAND_X");
     RHand_Y=Shared_Memory::getInstance().Register_Double_Input("RIGHT_HAND_Y");
     RHand_Z=Shared_Memory::getInstance().Register_Double_Input("RIGHT_HAND_Z");
     LShoulder_X=Shared_Memory::getInstance().Register_Double_Input("LEFT_SHOULDER_X");
     LShoulder_Y=Shared_Memory::getInstance().Register_Double_Input("LEFT_SHOULDER_Y");
     LShoulder_Z=Shared_Memory::getInstance().Register_Double_Input("LEFT_SHOULDER_Z");
     LElbow_X=Shared_Memory::getInstance().Register_Double_Input("LEFT_ELBOW_X");
     LElbow_Y=Shared_Memory::getInstance().Register_Double_Input("LEFT_ELBOW_Y");
     LElbow_Z=Shared_Memory::getInstance().Register_Double_Input("LEFT_ELBOW_Z");
     LHand_X=Shared_Memory::getInstance().Register_Double_Input("LEFT_HAND_X");
     LHand_Y=Shared_Memory::getInstance().Register_Double_Input("LEFT_HAND_Y");
     LHand_Z=Shared_Memory::getInstance().Register_Double_Input("LEFT_HAND_Z");
     Torso_X=Shared_Memory::getInstance().Register_Double_Input("TORSO_X");
     Torso_Y=Shared_Memory::getInstance().Register_Double_Input("TORSO_Y");
     Torso_Z=Shared_Memory::getInstance().Register_Double_Input("TORSO_Z");
     Head_X=Shared_Memory::getInstance().Register_Double_Input("HEAD_X");
     Head_Y=Shared_Memory::getInstance().Register_Double_Input("HEAD_Y");
     Head_Z=Shared_Memory::getInstance().Register_Double_Input("HEAD_Z");
 /*
     BTGripper_X=Shared_Memory::getInstance().Register_Double_Input("BTGripper_X");
     BTGripper_Y=Shared_Memory::getInstance().Register_Double_Input("BTGripper_Y");
     BTGripper_Z=Shared_Memory::getInstance().Register_Double_Input("BTGripper_Z");*/
     LPMS_QUAT_W=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_W");
     LPMS_QUAT_X=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_X");
     LPMS_QUAT_Y=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_Y");
     LPMS_QUAT_Z=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_Z");
     LPMS_QUAT_W=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_W");
     LPMS_QUAT_X=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_X");
     LPMS_QUAT_Y=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_Y");
     LPMS_QUAT_Z=Shared_Memory::getInstance().Register_Double_Input("LPMS_QUAT_Z");
     LPMS_ACCEL_RAW_X=Shared_Memory::getInstance().Register_Double_Input("LPMS_ACCEL_RAW_X");
     LPMS_ACCEL_RAW_Y=Shared_Memory::getInstance().Register_Double_Input("LPMS_ACCEL_RAW_Y");
     LPMS_ACCEL_RAW_Z=Shared_Memory::getInstance().Register_Double_Input("LPMS_ACCEL_RAW_Z");
     LPMS_GYRO_RAW_X=Shared_Memory::getInstance().Register_Double_Input("LPMS_GYRO_RAW_X");
     LPMS_GYRO_RAW_Y=Shared_Memory::getInstance().Register_Double_Input("LPMS_GYRO_RAW_Y");
     LPMS_GYRO_RAW_Z=Shared_Memory::getInstance().Register_Double_Input("LPMS_GYRO_RAW_Z");
     LPMS_MAT_11=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_11");
     LPMS_MAT_12=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_12");
     LPMS_MAT_13=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_13");
     LPMS_MAT_21=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_21");
     LPMS_MAT_22=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_22");
     LPMS_MAT_23=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_23");
     LPMS_MAT_31=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_31");
     LPMS_MAT_32=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_32");
     LPMS_MAT_33=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_33");
     LPMS_MAT_OFFSET_11=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_11");
     LPMS_MAT_OFFSET_12=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_12");
     LPMS_MAT_OFFSET_13=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_13");
     LPMS_MAT_OFFSET_21=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_21");
     LPMS_MAT_OFFSET_22=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_22");
     LPMS_MAT_OFFSET_23=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_23");
     LPMS_MAT_OFFSET_31=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_31");
     LPMS_MAT_OFFSET_32=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_32");
     LPMS_MAT_OFFSET_33=Shared_Memory::getInstance().Register_Double_Input("LPMS_MAT_OFFSET_33");
     return true;
 }
Initialize_Output()
bool File_Writer::Initialize_Output () virtual
Initialize Output variables for the plugin to publish.
Returns
bool
Implements IPlugin.
Definition at line 145 of file Main.cpp.
 {
     return true;
 }
loadConfiguration()
bool File_Writer::loadConfiguration () virtual
Load configuration.
The configuration can be loaded from file, or be hard coded into the plugin (not recomended), initialization of public and private variables should occur here
By default loadConfiguration is called during PluginManager::Initialize() by the plugin manager.
Returns
bool
Implements IPlugin.
Definition at line 126 of file Main.cpp.
 {
     std::stringstream path;
     path <<"../conf/" << PLUGIN_NAME;
     ConfigFile config( path.str() );
     return true;
 }
Main()
void File_Writer::Main () virtual
Main funcction of the plugin.
Started in a new thread by the Run() funcction is the most importatn funcction of the plugin. Infinite loop (generaly a while(running) function that runs undefenitly in a read/process/write cicle).
Returns
void
Implements IPlugin.
Definition at line 49 of file Main.cpp.
References saveConfiguration().
 {
     #ifdef OPENGL_GUI
     Gui::getInstance();
     Tab *pluginTab;
     pluginTab = new Tab("File_Writer");
     Gui::getInstance().setActiveTab("File_Writer");
     #endif
     std::ofstream myfile;
     while(running)
     {
         if(InputSingleton::getInstance().key==32)
         {
             InputSingleton::getInstance().key=NULL;
             if(recording==false)
             {
                 recording=true;
                 std::cout << "Start Recording " << std::endl;
                 std::stringstream sstm;
                 sstm << name << User_ID << "_" << counter << ".csv";
                 counter++;
                 myfile.open (sstm.str().c_str(), std::ios::out| std::ios::trunc );
                 sstm.str(" ");
                 myfile << "RShoulder_X,RShoulder_Y,RShoulder_Z,RElbow_X,RElbow_Y,RElbow_Z ,RHand_X,RHand_Y,RHand_Z," <<
                        "LShoulder_X,LShoulder_Y,LShoulder_Z,LElbow_X,LElbow_Y,LElbow_Z ,LHand_X,LHand_Y,LHand_Z," <<
                        "Torso_X,Torso_Y,Torso_Z,Head_X,Head_Y,Head_Z," <<
 //                        "BTGripper_X,BTGripper_Y,BTGripper_Z," <<
                        "LPMS_QUAT_W,LPMS_QUAT_X,LPMS_QUAT_Y,LPMS_QUAT_Z," <<
                        "LPMS_ACCEL_RAW_X,LPMS_ACCEL_RAW_Y,LPMS_ACCEL_RAW_Z,"<<
                        "LPMS_GYRO_RAW_X,LPMS_GYRO_RAW_Y,LPMS_GYRO_RAW_Z," <<
                        "LPMS_MAT_11,LPMS_MAT_12,LPMS_MAT_13,LPMS_MAT_21,LPMS_MAT_22,LPMS_MAT_23,LPMS_MAT_31,LPMS_MAT_32,LPMS_MAT_33," <<
                        "LPMS_MAT_OFFSET_11,LPMS_MAT_OFFSET_12,LPMS_MAT_OFFSET_13,LPMS_MAT_OFFSET_21,LPMS_MAT_OFFSET_22,LPMS_MAT_OFFSET_23," <<
                        "LPMS_MAT_OFFSET_31,LPMS_MAT_OFFSET_32,LPMS_MAT_OFFSET_33\n";
             }
             else
             {
                 recording=false;
                 std::cout << "Stop Recording " << std::endl;
                 myfile.close();
             }
         }
         if(recording==true)
         {
             myfile << *RShoulder_X << "," << *RShoulder_Y << "," << *RShoulder_Z << "," << *RElbow_X << "," << *RElbow_Y << "," << *RElbow_Z  << "," << *RHand_X << "," << *RHand_Y << "," << *RHand_Z << "," ;
             myfile << *LShoulder_X << "," << *LShoulder_Y << "," << *LShoulder_Z << "," << *LElbow_X << "," << *LElbow_Y << "," << *LElbow_Z  << "," << *LHand_X << "," << *LHand_Y << "," << *LHand_Z << "," ;
             myfile << *Torso_X << "," << *Torso_Y << "," << *Torso_Z << "," << *Head_X << "," << *Head_Y << "," << *Head_Z << "," ;
 //             myfile << *BTGripper_X << "," << *BTGripper_Y << "," << *BTGripper_Z << "," ;
             myfile << *LPMS_QUAT_W << "," << *LPMS_QUAT_X << "," << *LPMS_QUAT_Y << "," << *LPMS_QUAT_Z << "," ;
             myfile << *LPMS_ACCEL_RAW_X << "," << *LPMS_ACCEL_RAW_Y << "," << *LPMS_ACCEL_RAW_Z << "," ;
             myfile << *LPMS_GYRO_RAW_X << "," << *LPMS_GYRO_RAW_Y << "," << *LPMS_GYRO_RAW_Z << "," ;
             myfile << *LPMS_MAT_11 << "," << *LPMS_MAT_12 << "," << *LPMS_MAT_13 << "," ;
             myfile << *LPMS_MAT_21 << "," << *LPMS_MAT_22 << "," << *LPMS_MAT_23 << "," ;
             myfile << *LPMS_MAT_31 << "," << *LPMS_MAT_32 << "," << *LPMS_MAT_33 << "," ;
             myfile << *LPMS_MAT_OFFSET_11 << "," << *LPMS_MAT_OFFSET_12 << "," << *LPMS_MAT_OFFSET_13 << "," ;
             myfile << *LPMS_MAT_OFFSET_21 << "," << *LPMS_MAT_OFFSET_22 << "," << *LPMS_MAT_OFFSET_23 << "," ;
             myfile << *LPMS_MAT_OFFSET_31 << "," << *LPMS_MAT_OFFSET_32 << "," << *LPMS_MAT_OFFSET_33 << "\n";
         }
         //Shared_Memory::getInstance().Print_Double_Values();
         usleep(500);
     }
     saveConfiguration();
     myfile.close();
     stoped=true;
     return;
 }
run()
void File_Writer::run () virtual
Execute plugin.
Starts a new thread and executes the plugins main() funcction.
Returns
void
Implements IPlugin.
Definition at line 227 of file Main.cpp.
References IPlugin::IncWrapper().
 {
     pthread_create(&thread_id, NULL, &IPlugin::IncWrapper, this);
     running = true;
     stoped = false;
 }
saveConfiguration()
bool File_Writer::saveConfiguration () virtual
Save configuration.
The configuration should be saved to file, public and private variables that should be configured at startup should be saved.
By default saveConfiguration is called during PluginManager::Unload() by the plugin manager.
Returns
bool
Implements IPlugin.
Definition at line 134 of file Main.cpp.
Referenced by Main().
 {
     std::stringstream path;
     path <<"../conf/" << PLUGIN_NAME;
     ConfigFile config( path.str() );
     std::ofstream file(path.str());
     file << config;
     file.close();
     return true;
 }
stop()
void File_Writer::stop () virtual
Stop plugin.
Stops the plugin
Returns
void
Implements IPlugin.
Definition at line 234 of file Main.cpp.
 {
     running = false;
 }
The documentation for this class was generated from the following files:
/home/patrick/projects/Gesture_Therapy_Linux/src/File_Writer/File_Writer.h
/home/patrick/projects/Gesture_Therapy_Linux/src/File_Writer/Main.cpp