Sabina: TUIO::TuioListener Class Reference
TUIO::TuioListener Class Reference abstract
#include <TuioListener.h>
Public Member Functions
virtual ~TuioListener ()
virtual void addTuioObject (TuioObject *tobj)=0
virtual void updateTuioObject (TuioObject *tobj)=0
virtual void removeTuioObject (TuioObject *tobj)=0
virtual void addTuioCursor (TuioCursor *tcur)=0
virtual void updateTuioCursor (TuioCursor *tcur)=0
virtual void removeTuioCursor (TuioCursor *tcur)=0
virtual void refresh (TuioTime ftime)=0
Detailed Description
The TuioListener interface provides a simple callback infrastructure which is used by the TuioClient class to dispatch TUIO events to all registered instances of classes that implement the TuioListener interface defined here.
Any class that implements the TuioListener interface is required to implement all of the callback methods defined here. The TuioClient makes use of these interface methods in order to dispatch TUIO events to all registered TuioListener implementations.
public class MyTuioListener implements TuioListener
...
MyTuioListener listener = new MyTuioListener();
TuioClient client = new TuioClient();
client.addTuioListener(listener);
client.start();
Author
Martin Kaltenbrunner
Version
1.4
Definition at line 47 of file TuioListener.h.
Constructor & Destructor Documentation
~TuioListener()
virtual TUIO::TuioListener::~TuioListener () inline virtual
The destructor is doing nothing in particular.
Definition at line 53 of file TuioListener.h.
References addTuioCursor(), addTuioObject(), refresh(), removeTuioCursor(), removeTuioObject(), updateTuioCursor(), and updateTuioObject().
 {};
Member Function Documentation
addTuioCursor()
virtual void TUIO::TuioListener::addTuioCursor (TuioCursor * tcur) pure virtual
This callback method is invoked by the TuioClient when a new TuioCursor is added to the session.
Parameters
tcur the TuioCursor reference associated to the addTuioCursor event
Implemented in TuioDump.
Referenced by ~TuioListener().
addTuioObject()
virtual void TUIO::TuioListener::addTuioObject (TuioObject * tobj) pure virtual
This callback method is invoked by the TuioClient when a new TuioObject is added to the session.
Parameters
tobj the TuioObject reference associated to the addTuioObject event
Implemented in TuioDump.
Referenced by ~TuioListener().
refresh()
virtual void TUIO::TuioListener::refresh (TuioTime ftime) pure virtual
This callback method is invoked by the TuioClient to mark the end of a received TUIO message bundle.
Parameters
ftime the TuioTime associated to the current TUIO message bundle
Implemented in TuioDump.
Referenced by ~TuioListener().
removeTuioCursor()
virtual void TUIO::TuioListener::removeTuioCursor (TuioCursor * tcur) pure virtual
This callback method is invoked by the TuioClient when an existing TuioCursor is removed from the session.
Parameters
tcur the TuioCursor reference associated to the removeTuioCursor event
Implemented in TuioDump.
Referenced by ~TuioListener().
removeTuioObject()
virtual void TUIO::TuioListener::removeTuioObject (TuioObject * tobj) pure virtual
This callback method is invoked by the TuioClient when an existing TuioObject is removed from the session.
Parameters
tobj the TuioObject reference associated to the removeTuioObject event
Implemented in TuioDump.
Referenced by ~TuioListener().
updateTuioCursor()
virtual void TUIO::TuioListener::updateTuioCursor (TuioCursor * tcur) pure virtual
This callback method is invoked by the TuioClient when an existing TuioCursor is updated during the session.
Parameters
tcur the TuioCursor reference associated to the updateTuioCursor event
Implemented in TuioDump.
Referenced by ~TuioListener().
updateTuioObject()
virtual void TUIO::TuioListener::updateTuioObject (TuioObject * tobj) pure virtual
This callback method is invoked by the TuioClient when an existing TuioObject is updated during the session.
Parameters
tobj the TuioObject reference associated to the updateTuioObject event
Implemented in TuioDump.
Referenced by ~TuioListener().
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioListener.h