Sabina: CJoypad Class Reference
CJoypad Class Reference
#include <Joypad.h>
Public Member Functions
const char *const InstanceName () const
const char *const ProductName () const
const unsigned short NumButtons () const
const unsigned short NumPovs () const
bool HasX () const
bool HasY () const
bool HasZ () const
bool HasXrot () const
bool HasYrot () const
bool HasZrot () const
bool HasExtra1 () const
bool HasExtra2 () const
const bool Button (const unsigned int &i) const
const LONG Xaxis () const
X-axis, usually the left-right movement of a stick.
const LONG Xvelocity () const
X-axis velocity.
const LONG Xacceleration () const
X-axis acceleration.
const LONG Xforce () const
X-axis force.
const LONG Yaxis () const
Y-axis, usually the forward-backward movement of a stick.
const LONG Yvelocity () const
Y-axis velocity.
const LONG Yacceleration () const
Y-axis acceleration.
const LONG Yforce () const
Y-axis force.
const LONG Zaxis () const
const LONG Zvelocity () const
Z-axis velocity.
const LONG Zacceleration () const
Z-axis acceleration.
const LONG Zforce () const
Z-axis force.
const LONG Xrot () const
X-axis rotation. If the joystick does not have this axis, the value is 0.
const LONG XrotVelocity () const
X-axis angular velocity.
const LONG XrotAcceleration () const
X-axis angular acceleration.
const LONG XrotForce () const
X-axis torque.
const LONG Yrot () const
Y-axis rotation. If the joystick does not have this axis, the value is 0.
const LONG YrotVelocity () const
Y-axis angular velocity.
const LONG YrotAcceleration () const
Y-axis angular acceleration.
const LONG YrotForce () const
Y-axis torque.
const LONG Zrot () const
const LONG ZrotVelocity () const
Z-axis angular velocity. .
const LONG ZrotAcceleration () const
Z-axis angular acceleration.
const LONG ZrotForce () const
Z-axis torque.
const LONG ExtraAxes (const unsigned int &i) const
const LONG ExtraVelocities (const unsigned int &i) const
const LONG ExtraAccelerations (const unsigned int &i) const
const LONG ExtraForces (const unsigned int &i) const
const DWORD POV (const unsigned int &i) const
Friends
bool InitInput ()
Initialize the DirectInput variables.
bool UpdateInputState ()
You should call this to update the state of the joypad.
void FreeInput ()
Cleans up Direct Input.
Additional Inherited Members
Public Types inherited from XInputJoypad
enum eAxes {
X_AXIS = 0x00000001, Y_AXIS = 0x00000002, Z_AXIS = 0x00000004, X_ROT_AXIS = 0x00000008,
Y_ROT_AXIS = 0x00000010, Z_ROT_AXIS = 0x00000020, SLIDER_1 = 0x00000040, SLIDER_2 = 0x00000080,
AXIS_LAST = 0xFFFFFFFF
}
an enumeration to represent the various axes that may be available
Detailed Description
The Linux implimentation of the joypad interface class.
Definition at line 588 of file Joypad.h.
Member Function Documentation
Button()
const bool CJoypad::Button (const unsigned int & i) const inline virtual
Array of buttons. The high-order bit of the byte is set if the corresponding button is down, and clear if the button is up or does not exist.
Implements XInputJoypad.
Definition at line 655 of file Joypad.h.
{
         return Buttons[i] != 0;
     }
ExtraAxes()
const LONG CJoypad::ExtraAxes (const unsigned int & i) const inline virtual
Two additional axis values (formerly called the u-axis and v-axis) whose semantics depend on the joystick. Use the IDirectInputDevice8::GetObjectInfo method to obtain semantic information about these values.
Implements XInputJoypad.
Definition at line 791 of file Joypad.h.
{
         return Axes[6+i];
     }
HasX()
bool CJoypad::HasX () const inline virtual
the following functions allow you to check to see if the specified axis is available on the joypad.
Implements XInputJoypad.
Definition at line 623 of file Joypad.h.
                       {
         return m_iAxes>=1;
     }
NumButtons()
const unsigned short CJoypad::NumButtons () const inline virtual
this function returns the number of buttons available on the joypad
Implements XInputJoypad.
Definition at line 607 of file Joypad.h.
{
         return m_nButtons;
     }
NumPovs()
const unsigned short CJoypad::NumPovs () const inline virtual
this function returns the number of buttons available on the joypad
Implements XInputJoypad.
Definition at line 614 of file Joypad.h.
{
         return 0;
     }
POV()
const DWORD CJoypad::POV (const unsigned int & i) const inline virtual
Direction controllers, such as point-of-view hats. The position is indicated in hundredths of a degree clockwise from north (away from the user). The center position is normally reported as -1; but see Remarks. For indicators that have only five positions, the value for a controller is -1, 0, 9,000, 18,000, or 27,000.
Implements XInputJoypad.
Definition at line 815 of file Joypad.h.
References FreeInput(), InitInput(), and UpdateInputState().
{
         return 0;
     }
Zaxis()
const LONG CJoypad::Zaxis () const inline virtual
Z-axis, often the throttle control. If the joystick does not have this axis, the value is 0.
Implements XInputJoypad.
Definition at line 706 of file Joypad.h.
{
         return Axes[2];
     }
Zrot()
const LONG CJoypad::Zrot () const inline virtual
Z-axis rotation (often called the rudder). If the joystick does not have this axis, the value is 0.
Implements XInputJoypad.
Definition at line 769 of file Joypad.h.
{
         return Axes[5];
     }
Friends And Related Function Documentation
InitInput
bool InitInput () friend
Initialize the DirectInput variables.
Returns
true if OK
true if OK, false if it fails
Definition at line 383 of file Joypad.cpp.
 {
     bool ret=false;
     int fd;
     if ( (fd = open("/dev/input/js0", O_RDONLY)) > 0 )
     {
         CJoypad* ptr = new CJoypad;
         ioctl(fd, JSIOCGVERSION, &ptr->version);
         ioctl(fd, JSIOCGAXES, &ptr->m_iAxes);
         ioctl(fd, JSIOCGBUTTONS, &ptr->m_nButtons);
         ioctl(fd, JSIOCGNAME(NAME_LENGTH), ptr->name);
         fcntl(fd, F_SETFL, O_NONBLOCK);
         ptr->fd = fd;
         g_aJoypads.push_back(ptr);
         ret=true;
     }
     return ret;
 }
UpdateInputState
bool UpdateInputState () friend
You should call this to update the state of the joypad.
Returns
true if OK.
Definition at line 370 of file Joypad.cpp.
 {
     std::vector< XInputJoypad* >::iterator it = g_aJoypads.begin();
     for( ; it != g_aJoypads.end(); ++it )
     {
         (*it)->Update();
     }
 }
The documentation for this class was generated from the following files:
/home/patrick/projects/Gesture_Therapy_Linux/src/Joystick_Reader/Joypad.h
/home/patrick/projects/Gesture_Therapy_Linux/src/Joystick_Reader/Joypad.cpp