Sabina: TUIO::TuioCursor Class Reference
TUIO::TuioCursor Class Reference
#include <TuioCursor.h>
Public Member Functions
TuioCursor (TuioTime ttime, long si, int ci, float xp, float yp)
TuioCursor (long si, int ci, float xp, float yp)
TuioCursor (TuioCursor *tcur)
~TuioCursor ()
int getCursorID ()
Public Member Functions inherited from TUIO::TuioContainer
TuioContainer (TuioTime ttime, long si, float xp, float yp)
TuioContainer (long si, float xp, float yp)
TuioContainer (TuioContainer *tcon)
virtual ~TuioContainer ()
virtual void update (TuioTime ttime, float xp, float yp)
virtual void stop (TuioTime ttime)
virtual void update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma)
virtual void update (float xp, float yp, float xs, float ys, float ma)
virtual void update (TuioContainer *tcon)
virtual void remove (TuioTime ttime)
virtual long getSessionID ()
virtual float getXSpeed ()
virtual float getYSpeed ()
virtual TuioPoint getPosition ()
virtual std::list< TuioPoint > getPath ()
virtual float getMotionSpeed ()
virtual float getMotionAccel ()
virtual int getTuioState ()
virtual bool isMoving ()
Public Member Functions inherited from TUIO::TuioPoint
TuioPoint (float xp, float yp)
TuioPoint (TuioTime ttime, float xp, float yp)
TuioPoint (TuioPoint *tpoint)
~TuioPoint ()
void update (TuioPoint *tpoint)
void update (float xp, float yp)
void update (TuioTime ttime, float xp, float yp)
float getX ()
float getY ()
float getDistance (float xp, float yp)
float getDistance (TuioPoint *tpoint)
float getAngle (float xp, float yp)
float getAngle (TuioPoint *tpoint)
float getAngleDegrees (float xp, float yp)
float getAngleDegrees (TuioPoint *tpoint)
int getScreenX (int width)
int getScreenY (int height)
TuioTime getTuioTime ()
TuioTime getStartTime ()
Protected Attributes
int cursor_id
Protected Attributes inherited from TUIO::TuioContainer
long session_id
float x_speed
float y_speed
float motion_speed
float motion_accel
std::list< TuioPoint > path
int state
Protected Attributes inherited from TUIO::TuioPoint
float xpos
float ypos
TuioTime currentTime
TuioTime startTime
Detailed Description
The TuioCursor class encapsulates /tuio/2Dcur TUIO cursors.
Author
Martin Kaltenbrunner
Version
1.4
Definition at line 36 of file TuioCursor.h.
Constructor & Destructor Documentation
TuioCursor() [1/3]
TUIO::TuioCursor::TuioCursor (TuioTime ttime, long si, int ci, float xp, float yp) inline
This constructor takes a TuioTime argument and assigns it along with the provided Session ID, Cursor ID, X and Y coordinate to the newly created TuioCursor.
Parameters
ttime the TuioTime to assign
si the Session ID to assign
ci the Cursor ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 55 of file TuioCursor.h.
                                                                         :TuioContainer(ttime,si,xp,yp) {
             cursor_id = ci;
         };
TuioCursor() [2/3]
TUIO::TuioCursor::TuioCursor (long si, int ci, float xp, float yp) inline
This constructor takes the provided Session ID, Cursor ID, X and Y coordinate and assigs these values to the newly created TuioCursor.
Parameters
si the Session ID to assign
ci the Cursor ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 68 of file TuioCursor.h.
                                                         :TuioContainer(si,xp,yp) {
             cursor_id = ci;
         };
TuioCursor() [3/3]
TUIO::TuioCursor::TuioCursor (TuioCursor * tcur) inline
This constructor takes the atttibutes of the provided TuioCursor and assigs these values to the newly created TuioCursor.
Parameters
tcur the TuioCursor to assign
Definition at line 78 of file TuioCursor.h.
References getCursorID().
                                      :TuioContainer(tcur) {
             cursor_id = tcur->getCursorID();
         };
~TuioCursor()
TUIO::TuioCursor::~TuioCursor () inline
The destructor is doing nothing in particular.
Definition at line 85 of file TuioCursor.h.
 {};
Member Function Documentation
getCursorID()
int TUIO::TuioCursor::getCursorID () inline
Returns the Cursor ID of this TuioCursor.
Returns
the Cursor ID of this TuioCursor
Definition at line 91 of file TuioCursor.h.
References cursor_id.
Referenced by TuioDump::addTuioCursor(), TuioDump::removeTuioCursor(), TuioCursor(), and TuioDump::updateTuioCursor().
{
             return cursor_id;
         };
Member Data Documentation
cursor_id
int TUIO::TuioCursor::cursor_id protected
The individual cursor ID number that is assigned to each TuioCursor.
Definition at line 42 of file TuioCursor.h.
Referenced by getCursorID().
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioCursor.h