Sabina: TUIO::TuioObject Class Reference
TUIO::TuioObject Class Reference
#include <TuioObject.h>
Public Member Functions
TuioObject (TuioTime ttime, long si, int sym, float xp, float yp, float a)
TuioObject (long si, int sym, float xp, float yp, float a)
TuioObject (TuioObject *tobj)
~TuioObject ()
void update (TuioTime ttime, float xp, float yp, float a, float xs, float ys, float rs, float ma, float ra)
void update (float xp, float yp, float a, float xs, float ys, float rs, float ma, float ra)
void update (TuioTime ttime, float xp, float yp, float a)
void stop (TuioTime ttime)
void update (TuioObject *tobj)
int getSymbolID ()
float getAngle ()
float getAngleDegrees ()
float getRotationSpeed ()
float getRotationAccel ()
virtual bool isMoving ()
Public Member Functions inherited from TUIO::TuioContainer
TuioContainer (TuioTime ttime, long si, float xp, float yp)
TuioContainer (long si, float xp, float yp)
TuioContainer (TuioContainer *tcon)
virtual ~TuioContainer ()
virtual void update (TuioTime ttime, float xp, float yp)
virtual void update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma)
virtual void update (float xp, float yp, float xs, float ys, float ma)
virtual void update (TuioContainer *tcon)
virtual void remove (TuioTime ttime)
virtual long getSessionID ()
virtual float getXSpeed ()
virtual float getYSpeed ()
virtual TuioPoint getPosition ()
virtual std::list< TuioPoint > getPath ()
virtual float getMotionSpeed ()
virtual float getMotionAccel ()
virtual int getTuioState ()
Public Member Functions inherited from TUIO::TuioPoint
TuioPoint (float xp, float yp)
TuioPoint (TuioTime ttime, float xp, float yp)
TuioPoint (TuioPoint *tpoint)
~TuioPoint ()
void update (TuioPoint *tpoint)
void update (float xp, float yp)
void update (TuioTime ttime, float xp, float yp)
float getX ()
float getY ()
float getDistance (float xp, float yp)
float getDistance (TuioPoint *tpoint)
float getAngle (float xp, float yp)
float getAngle (TuioPoint *tpoint)
float getAngleDegrees (float xp, float yp)
float getAngleDegrees (TuioPoint *tpoint)
int getScreenX (int width)
int getScreenY (int height)
TuioTime getTuioTime ()
TuioTime getStartTime ()
Protected Attributes
int symbol_id
float angle
float rotation_speed
float rotation_accel
Protected Attributes inherited from TUIO::TuioContainer
long session_id
float x_speed
float y_speed
float motion_speed
float motion_accel
std::list< TuioPoint > path
int state
Protected Attributes inherited from TUIO::TuioPoint
float xpos
float ypos
TuioTime currentTime
TuioTime startTime
Detailed Description
The TuioObject class encapsulates /tuio/2Dobj TUIO objects.
Author
Martin Kaltenbrunner
Version
1.4
Definition at line 38 of file TuioObject.h.
Constructor & Destructor Documentation
TuioObject() [1/3]
TUIO::TuioObject::TuioObject (TuioTime ttime, long si, int sym, float xp, float yp, float a) inline
This constructor takes a TuioTime argument and assigns it along with the provided Session ID, Symbol ID, X and Y coordinate and angle to the newly created TuioObject.
Parameters
ttime the TuioTime to assign
si the Session ID to assign
sym the Symbol ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
Definition at line 70 of file TuioObject.h.
                                                                                   :TuioContainer(ttime, si, xp, yp) {
             symbol_id = sym;
             angle = a;
             rotation_speed = 0.0f;
             rotation_accel = 0.0f;
         };
TuioObject() [2/3]
TUIO::TuioObject::TuioObject (long si, int sym, float xp, float yp, float a) inline
This constructor takes the provided Session ID, Symbol ID, X and Y coordinate and angle, and assigs these values to the newly created TuioObject.
Parameters
si the Session ID to assign
sym the Symbol ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
Definition at line 87 of file TuioObject.h.
                                                                   :TuioContainer(si, xp, yp) {
             symbol_id = sym;
             angle = a;
             rotation_speed = 0.0f;
             rotation_accel = 0.0f;
         };
TuioObject() [3/3]
TUIO::TuioObject::TuioObject (TuioObject * tobj) inline
This constructor takes the atttibutes of the provided TuioObject and assigs these values to the newly created TuioObject.
Parameters
tobj the TuioObject to assign
Definition at line 100 of file TuioObject.h.
References getAngle(), and getSymbolID().
                                      :TuioContainer(tobj) {
             symbol_id = tobj->getSymbolID();
             angle = tobj->getAngle();
             rotation_speed = 0.0f;
             rotation_accel = 0.0f;
         };
~TuioObject()
TUIO::TuioObject::~TuioObject () inline
The destructor is doing nothing in particular.
Definition at line 110 of file TuioObject.h.
 {};
Member Function Documentation
getAngle()
float TUIO::TuioObject::getAngle () inline
Returns the rotation angle of this TuioObject.
Returns
the rotation angle of this TuioObject
Definition at line 222 of file TuioObject.h.
References angle.
Referenced by TuioDump::addTuioObject(), TuioObject(), update(), and TuioDump::updateTuioObject().
{
             return angle;
         };
getAngleDegrees()
float TUIO::TuioObject::getAngleDegrees () inline
Returns the rotation angle in degrees of this TuioObject.
Returns
the rotation angle in degrees of this TuioObject
Definition at line 230 of file TuioObject.h.
{
             return (float)(angle/M_PI*180);
         };
getRotationAccel()
float TUIO::TuioObject::getRotationAccel () inline
Returns the rotation acceleration of this TuioObject.
Returns
the rotation acceleration of this TuioObject
Definition at line 246 of file TuioObject.h.
References rotation_accel.
Referenced by update(), and TuioDump::updateTuioObject().
{
             return rotation_accel;
         };
getRotationSpeed()
float TUIO::TuioObject::getRotationSpeed () inline
Returns the rotation speed of this TuioObject.
Returns
the rotation speed of this TuioObject
Definition at line 238 of file TuioObject.h.
References rotation_speed.
Referenced by update(), and TuioDump::updateTuioObject().
{
             return rotation_speed;
         };
getSymbolID()
int TUIO::TuioObject::getSymbolID () inline
Returns the symbol ID of this TuioObject.
Returns
the symbol ID of this TuioObject
Definition at line 214 of file TuioObject.h.
References symbol_id.
Referenced by TuioDump::addTuioObject(), TuioDump::removeTuioObject(), TuioObject(), and TuioDump::updateTuioObject().
{
             return symbol_id;
         };
isMoving()
virtual bool TUIO::TuioObject::isMoving () inline virtual
Returns true of this TuioObject is moving.
Returns
true of this TuioObject is moving
Reimplemented from TUIO::TuioContainer.
Definition at line 254 of file TuioObject.h.
References TUIO::TuioContainer::state.
{
             if ((state==TUIO_ACCELERATING) || (state==TUIO_DECELERATING) || (state==TUIO_ROTATING)) return true;
             else return false;
         };
stop()
void TUIO::TuioObject::stop (TuioTime ttime) inline virtual
This method is used to calculate the speed and acceleration values of a TuioObject with unchanged position and angle.
Reimplemented from TUIO::TuioContainer.
Definition at line 191 of file TuioObject.h.
References update(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
{
             update(ttime,xpos,ypos,angle);
         };
update() [1/4]
void TUIO::TuioObject::update (TuioTime ttime, float xp, float yp, float a, float xs, float ys, float rs, float ma, float ra) inline
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate, angle, X and Y velocity, motion acceleration, rotation speed and rotation acceleration to the private TuioObject attributes.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
rs the rotation velocity to assign
ma the motion acceleration to assign
ra the rotation acceleration to assign
Definition at line 127 of file TuioObject.h.
References TUIO::TuioContainer::state, and TUIO::TuioContainer::update().
Referenced by stop().
{
             TuioContainer::update(ttime,xp,yp,xs,ys,ma);
             angle = a;
             rotation_speed = rs;
             rotation_accel = ra;
             if ((rotation_accel!=0) && (state==TUIO_STOPPED)) state = TUIO_ROTATING;
         };
update() [2/4]
void TUIO::TuioObject::update (float xp, float yp, float a, float xs, float ys, float rs, float ma, float ra) inline
Assigns the provided X and Y coordinate, angle, X and Y velocity, motion acceleration rotation velocity and rotation acceleration to the private TuioContainer attributes. The TuioTime time stamp remains unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
rs the rotation velocity to assign
ma the motion acceleration to assign
ra the rotation acceleration to assign
Definition at line 149 of file TuioObject.h.
References TUIO::TuioContainer::state, and TUIO::TuioContainer::update().
{
             TuioContainer::update(xp,yp,xs,ys,ma);
             angle = a;
             rotation_speed = rs;
             rotation_accel = ra;
             if ((rotation_accel!=0) && (state==TUIO_STOPPED)) state = TUIO_ROTATING;
         };
update() [3/4]
void TUIO::TuioObject::update (TuioTime ttime, float xp, float yp, float a) inline
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate and angle to the private TuioObject attributes. The speed and accleration values are calculated accordingly.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle coordinate to assign
Definition at line 167 of file TuioObject.h.
References angle, TUIO::TuioPoint::currentTime, TUIO::TuioTime::getTotalMilliseconds(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioContainer::path, rotation_speed, TUIO::TuioContainer::state, and TUIO::TuioContainer::update().
{
             TuioPoint lastPoint = path.back();
             TuioContainer::update(ttime,xp,yp);
             TuioTime diffTime = currentTime - lastPoint.getTuioTime();
             float dt = diffTime.getTotalMilliseconds()/1000.0f;
             float last_angle = angle;
             float last_rotation_speed = rotation_speed;
             angle = a;
             double da = (angle-last_angle)/(2*M_PI);
             if (da>M_PI*1.5) da-=(2*M_PI);
             else if (da<M_PI*1.5) da+=(2*M_PI);
             rotation_speed = (float)da/dt;
             rotation_accel =  (rotation_speed - last_rotation_speed)/dt;
             if ((rotation_accel!=0) && (state==TUIO_STOPPED)) state = TUIO_ROTATING;
         };
update() [4/4]
void TUIO::TuioObject::update (TuioObject * tobj) inline
Takes the atttibutes of the provided TuioObject and assigs these values to this TuioObject. The TuioTime time stamp of this TuioContainer remains unchanged.
Parameters
tobj the TuioContainer to assign
Definition at line 202 of file TuioObject.h.
References getAngle(), getRotationAccel(), getRotationSpeed(), TUIO::TuioContainer::state, and TUIO::TuioContainer::update().
{
             TuioContainer::update(tobj);
             angle = tobj->getAngle();
             rotation_speed = tobj->getRotationSpeed();
             rotation_accel = tobj->getRotationAccel();
             if ((rotation_accel!=0) && (state==TUIO_STOPPED)) state = TUIO_ROTATING;
         };
Member Data Documentation
angle
float TUIO::TuioObject::angle protected
The rotation angle value.
Definition at line 48 of file TuioObject.h.
Referenced by getAngle(), and update().
rotation_accel
float TUIO::TuioObject::rotation_accel protected
The rotation acceleration value.
Definition at line 56 of file TuioObject.h.
Referenced by getRotationAccel().
rotation_speed
float TUIO::TuioObject::rotation_speed protected
The rotation speed value.
Definition at line 52 of file TuioObject.h.
Referenced by getRotationSpeed(), and update().
symbol_id
int TUIO::TuioObject::symbol_id protected
The individual symbol ID number that is assigned to each TuioObject.
Definition at line 44 of file TuioObject.h.
Referenced by getSymbolID().
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioObject.h