Sabina: Joystick_Writer Class Reference
Joystick_Writer Class Reference
Joystick_Writer plugin.
#include <Joystick_Writer.h>
Public Member Functions
void Main ()
Main funcction of the plugin.
bool loadConfiguration ()
Load configuration.
bool saveConfiguration ()
Save configuration.
bool Initialize_Output ()
Initialize Output variables for the plugin to publish.
bool Initialize_Input ()
Initialize Input variables for the plugin to publish.
void Init_Joy ()
void run ()
Execute plugin.
void stop ()
Stop plugin.
Additional Inherited Members
Static Public Member Functions inherited from IPlugin
static void * IncWrapper (void *thisPtr)
Wrapps the Main function of the plugin object to ANSI C to be pased as a parameter to pthread_create.
Public Attributes inherited from IPlugin
pthread_t thread_id
bool running
bool stoped
Detailed Description
Joystick_Writer plugin.
This plugin is a legacy wrapper that alows us to use Hocoma's games with this architecture it writes output to a shared memory segment defined by hocoma that can not be changed
Author
Patrick Heyer, patri.nosp@m.ckhe.nosp@m.y@pro.nosp@m.digy.nosp@m..net..nosp@m.mx
Date
jul 13, 2014
Version
1.0
Definition at line 15 of file Joystick_Writer.h.
Member Function Documentation
Initialize_Input()
bool Joystick_Writer::Initialize_Input () virtual
Initialize Input variables for the plugin to publish.
Returns
bool
Implements IPlugin.
Definition at line 134 of file Main.cpp.
 {
     X_axis=Shared_Memory::getInstance().Register_Double_Input("Tracker_X");
     Y_axis=Shared_Memory::getInstance().Register_Double_Input("Tracker_Y");
     Z_axis=Shared_Memory::getInstance().Register_Double_Input("Tracker_Z");
     RX_axis=Shared_Memory::getInstance().Register_Double_Input("Position_For_Game_RX");
     RY_axis=Shared_Memory::getInstance().Register_Double_Input("Position_For_Game_RY");
     RZ_axis=Shared_Memory::getInstance().Register_Double_Input("Position_For_Game_RZ");
     return true;
 }
Initialize_Output()
bool Joystick_Writer::Initialize_Output () virtual
Initialize Output variables for the plugin to publish.
Returns
bool
Implements IPlugin.
Definition at line 129 of file Main.cpp.
 {
     return true;
 }
loadConfiguration()
bool Joystick_Writer::loadConfiguration () virtual
Load configuration.
The configuration can be loaded from file, or be hard coded into the plugin (not recomended), initialization of public and private variables should occur here
By default loadConfiguration is called during PluginManager::Initialize() by the plugin manager.
Returns
bool
Implements IPlugin.
Definition at line 119 of file Main.cpp.
 {
     return true;
 }
Main()
void Joystick_Writer::Main () virtual
Main funcction of the plugin.
Started in a new thread by the Run() funcction is the most importatn funcction of the plugin. Infinite loop (generaly a while(running) function that runs undefenitly in a read/process/write cicle).
Returns
void
Implements IPlugin.
Definition at line 57 of file Main.cpp.
References stop().
 {
     struct uinput_user_dev uidev;
     int                    i;
     int                    fd;
     fd = open("/dev/uinput", O_WRONLY | O_NONBLOCK);
     if(fd < 0)
         die("error: open");
     memset(&uidev, 0, sizeof(uidev));
     snprintf(uidev.name, UINPUT_MAX_NAME_SIZE, "Virtual_joystick");
     uidev.id.bustype = BUS_USB;
     uidev.id.vendor  = 0x1;
     uidev.id.product = 0x1;
     uidev.id.version = 1;
     ioctl (fd, UI_SET_EVBIT, EV_SYN);
     ioctl (fd, UI_SET_EVBIT, EV_ABS);
     ioctl (fd, UI_SET_EVBIT, EV_KEY);
     ioctl (fd, UI_SET_ABSBIT, ABS_X);
     ioctl (fd, UI_SET_ABSBIT, ABS_Y);
     ioctl (fd, UI_SET_ABSBIT, ABS_Z);
     ioctl (fd, UI_SET_ABSBIT, ABS_RX);
     ioctl (fd, UI_SET_ABSBIT, ABS_RY);
     ioctl (fd, UI_SET_ABSBIT, ABS_RZ);
     ioctl (fd, UI_SET_ABSBIT, ABS_RT);
     ioctl (fd, UI_SET_ABSBIT, ABS_MAX);
     for(i = 0; i < ABS_MAX; ++i)
     {
         uidev.absmax[i] = 511;
         uidev.absmin[i] = -512;
     }
     // Create device
     write (fd, &uidev, sizeof (uidev));
     if (ioctl (fd, UI_DEV_CREATE))
     {
         LOG(WARNING) << "Unable to create UIDEVUT device.";
         LOG(ERROR) << PluginDisplayName << " will NOT keep executing";
         stop();
     running=false;
     stoped = true;
     return;
     }
     while(running)
     {
         do_uinput(fd,ABS_X,*X_axis*32767, EV_ABS);
         do_uinput(fd,ABS_Y,*Y_axis*32767, EV_ABS);
         do_uinput(fd,ABS_Z,*Z_axis*32767, EV_ABS);
         do_uinput(fd,ABS_RX,*RX_axis*32767, EV_ABS);
         do_uinput(fd,ABS_RY,*RY_axis*32767, EV_ABS);
         do_uinput(fd,ABS_RZ,*RZ_axis*32767, EV_ABS);
     }
     stoped = true;
     return;
 }
run()
void Joystick_Writer::run () virtual
Execute plugin.
Starts a new thread and executes the plugins main() funcction.
Returns
void
Implements IPlugin.
Definition at line 145 of file Main.cpp.
References IPlugin::IncWrapper().
 {
     pthread_create(&thread_id, NULL, &IPlugin::IncWrapper, this);
     running = true;
     stoped = false;
 }
saveConfiguration()
bool Joystick_Writer::saveConfiguration () virtual
Save configuration.
The configuration should be saved to file, public and private variables that should be configured at startup should be saved.
By default saveConfiguration is called during PluginManager::Unload() by the plugin manager.
Returns
bool
Implements IPlugin.
Definition at line 124 of file Main.cpp.
 {
     return true;
 }
stop()
void Joystick_Writer::stop () virtual
Stop plugin.
Stops the plugin
Returns
void
Implements IPlugin.
Definition at line 153 of file Main.cpp.
Referenced by Main().
 {
     running = false;
 }
The documentation for this class was generated from the following files:
/home/patrick/projects/Gesture_Therapy_Linux/src/Joystick_Writer/Joystick_Writer.h
/home/patrick/projects/Gesture_Therapy_Linux/src/Joystick_Writer/Main.cpp