Sabina: Gui Class Reference
Gui Class Reference
Public Member Functions
void initialize (void)
void Draw ()
Draws the Gui and its sub elements on screen.
void update ()
Updates the Gui.
void proccesInput ()
void resize (int x, int y)
void setActiveTab (std::string value)
Sets the tab to be displayed.
void setActiveTab (int tab)
Sets the tab to be displayed.
void addTab (Tab *value)
int getActiveTab ()
Static Public Member Functions
static Gui & getInstance ()
Returns a pointer to the Gui object.
static void freeInstance (void)
Protected Member Functions
Gui (const Gui &other)
virtual Gui & operator= (const Gui &other)
Detailed Description
Definition at line 35 of file gui.h.
Member Function Documentation
Draw()
void Gui::Draw ()
Draws the Gui and its sub elements on screen.
Draws the Gui the tabs acces button and the activeTab
Definition at line 85 of file gui.cpp.
 {
     if(numTabs!=0)
     {
     float color[4];
     glLoadIdentity();
     glDisable ( GL_TEXTURE_2D );
     setOrthographicProjection ( width, height);
     int w=width/numTabs;
     int i=0;
     for( ListItor itor = tabList.begin(); itor != tabList.end(); ++itor )
     {
         uiSetRoundBox("1100");
         if (i==getActiveTab ())
         {
             gl_round_box_Hshade(GL_POLYGON,i*w+1,1,(i+1)*w,height*.02,height*.02*.5,"FFFFFF", "008800");
             (*itor)->Draw();
         }
         else
         {
             gl_round_box_Hshade(GL_POLYGON,i*w+1,1,(i+1)*w,height*.02,height*.02*.5,"FFFFFF", "444488");
         }
         drawText((w*i)+5, 15,(*itor)->get_Name(), "FFFFFF", 1 );
         i++;
     }
     resetPerspectiveProjection();
     }
 }
getInstance()
Gui & Gui::getInstance (void) static
Returns a pointer to the Gui object.
Returns a pointer to the only copy in memory of the Gui object. If no object exist it will initialize the instance befor returning the pointer
Returns
Gui
Definition at line 66 of file gui.cpp.
Referenced by File_Writer::Main(), Tuio_Client::Main(), Tab::Tab(), and update().
 {
     if ( guiSingleton == 0 )
     {
         guiSingleton = new Gui;
     }
     return *guiSingleton;
 }
setActiveTab() [1/2]
void Gui::setActiveTab (std::string value)
Sets the tab to be displayed.
Sets the tab to be displayed by the gui
Parameters
value is the name of the tab to display
Definition at line 231 of file gui.cpp.
Referenced by File_Writer::Main(), Tuio_Client::Main(), and update().
 {
     Var_type::iterator iter = pestana.begin();
     iter = pestana.find(value);
     if (iter != pestana.end() )
     {
       setActiveTab(iter->second);
     }
 }
setActiveTab() [2/2]
void Gui::setActiveTab (int tab)
Sets the tab to be displayed.
Sets the tab to be displayed by the gui
Parameters
value is the numerical ID of the tab to display
Definition at line 209 of file gui.cpp.
 {
     if(tabList.size()>tab)
     {
         selectedTab=tab;
     }
     int i=0;
     for( ListItor itor = tabList.begin(); itor != tabList.end(); ++itor )
     {
         if (i==getActiveTab ())
         {
             (*itor)->set_active(true);
         }
         else
         {
             (*itor)->set_active(false);
         }
         i++;
     }
 }
update()
void Gui::update ()
Updates the Gui.
Updates the Gui generaly not needed as Draw updates it
Definition at line 115 of file gui.cpp.
References getInstance(), and setActiveTab().
 {
     for( ListItor itor = tabList.begin(); itor != tabList.end(); ++itor )
     {
         (*itor)->Update();
     }
 }
The documentation for this class was generated from the following files:
/home/patrick/projects/Gesture_Therapy_Linux/src/Gui/gui.h
/home/patrick/projects/Gesture_Therapy_Linux/src/Gui/gui.cpp