Sabina: TUIO::TuioTime Class Reference
TUIO::TuioTime Class Reference
#include <TuioTime.h>
Public Member Functions
TuioTime ()
~TuioTime ()
TuioTime (long msec)
TuioTime (long sec, long usec)
TuioTime operator+ (long us)
TuioTime operator+ (TuioTime ttime)
TuioTime operator- (long us)
TuioTime operator- (TuioTime ttime)
void operator= (TuioTime ttime)
bool operator== (TuioTime ttime)
bool operator!= (TuioTime ttime)
void reset ()
long getSeconds ()
long getMicroseconds ()
long getTotalMilliseconds ()
Static Public Member Functions
static void initSession ()
static TuioTime getSessionTime ()
static TuioTime getStartTime ()
static TuioTime getSystemTime ()
Detailed Description
The TuioTime class is a simple structure that is used to reprent the time that has elapsed since the session start. The time is internally represented as seconds and fractions of microseconds which should be more than sufficient for gesture related timing requirements. Therefore at the beginning of a typical TUIO session the static method initSession() will set the reference time for the session. Another important static method getSessionTime will return a TuioTime object representing the time elapsed since the session start. The class also provides various addtional convience method, which allow some simple time arithmetics.
Author
Martin Kaltenbrunner
Version
1.4
Definition at line 48 of file TuioTime.h.
Constructor & Destructor Documentation
TuioTime() [1/3]
TUIO::TuioTime::TuioTime () inline
The default constructor takes no arguments and sets the Seconds and Microseconds attributes of the newly created TuioTime both to zero.
Definition at line 60 of file TuioTime.h.
Referenced by operator+(), and operator-().
                     {
             seconds = 0;
             micro_seconds = 0;
         };
~TuioTime()
TUIO::TuioTime::~TuioTime () inline
The destructor is doing nothing in particular.
Definition at line 68 of file TuioTime.h.
 {}
TuioTime() [2/3]
TUIO::TuioTime::TuioTime (long msec) inline
This constructor takes the provided time represented in total Milliseconds and assigs this value to the newly created TuioTime.
Parameters
msec the total time in Millseconds
Definition at line 76 of file TuioTime.h.
{
             seconds = msec/MSEC_SECOND;
             micro_seconds = USEC_MILLISECOND*(msec%MSEC_SECOND);
         };
TuioTime() [3/3]
TUIO::TuioTime::TuioTime (long sec, long usec) inline
This constructor takes the provided time represented in Seconds and Microseconds and assigs these value to the newly created TuioTime.
Parameters
sec the total time in seconds
usec the microseconds time component
Definition at line 88 of file TuioTime.h.
{
             seconds = sec;
             micro_seconds = usec;
         };
Member Function Documentation
getMicroseconds()
long TUIO::TuioTime::getMicroseconds () inline
Returns the TuioTime Microseconds component.
Returns
the TuioTime Microseconds component
Definition at line 208 of file TuioTime.h.
Referenced by operator!=(), operator+(), operator-(), operator=(), and operator==().
{
             return micro_seconds;
         };
getSeconds()
long TUIO::TuioTime::getSeconds () inline
Returns the TuioTime Seconds component.
Returns
the TuioTime Seconds component
Definition at line 200 of file TuioTime.h.
Referenced by operator!=(), operator+(), operator-(), operator=(), and operator==().
{
             return seconds;
         };
getSessionTime()
static TuioTime TUIO::TuioTime::getSessionTime () static
Returns the present TuioTime representing the time since session start.
Returns
the present TuioTime representing the time since session start
Referenced by getTotalMilliseconds(), and TUIO::TuioPoint::TuioPoint().
getStartTime()
static TuioTime TUIO::TuioTime::getStartTime () static
Returns the absolut TuioTime representing the session start.
Returns
the absolut TuioTime representing the session start
Referenced by getTotalMilliseconds().
getSystemTime()
static TuioTime TUIO::TuioTime::getSystemTime () static
Returns the absolut TuioTime representing the current system time.
Returns
the absolut TuioTime representing the current system time
Referenced by getTotalMilliseconds().
getTotalMilliseconds()
long TUIO::TuioTime::getTotalMilliseconds () inline
Returns the total TuioTime in Milliseconds.
Returns
the total TuioTime in Milliseconds
Definition at line 216 of file TuioTime.h.
References getSessionTime(), getStartTime(), getSystemTime(), and initSession().
Referenced by TUIO::TuioContainer::update(), and TUIO::TuioObject::update().
{
             return seconds*MSEC_SECOND+micro_seconds/MSEC_SECOND;
         };
initSession()
static void TUIO::TuioTime::initSession () static
This static method globally resets the TUIO session time.
Referenced by getTotalMilliseconds().
operator!=()
bool TUIO::TuioTime::operator!= (TuioTime ttime) inline
Takes a TuioTime argument and compares the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to compare
Returns
true if the two TuioTime have differnt Seconds or Microseconds attributes
Definition at line 183 of file TuioTime.h.
References getMicroseconds(), and getSeconds().
{
             if ((seconds!=(long)ttime.getSeconds()) || (micro_seconds!=(long)ttime.getMicroseconds())) return true;
             else return false;
         };
operator+() [1/2]
TuioTime TUIO::TuioTime::operator+ (long us) inline
Sums the provided time value represented in total Microseconds to this TuioTime.
Parameters
us the total time to add in Microseconds
Returns
the sum of this TuioTime with the provided argument in microseconds
Definition at line 99 of file TuioTime.h.
References TuioTime().
{
             long sec = seconds + us/USEC_SECOND;
             long usec = micro_seconds + us%USEC_SECOND;
             return TuioTime(sec,usec);
         };
operator+() [2/2]
TuioTime TUIO::TuioTime::operator+ (TuioTime ttime) inline
Sums the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to add
Returns
the sum of this TuioTime with the provided TuioTime argument
Definition at line 111 of file TuioTime.h.
References getMicroseconds(), getSeconds(), and TuioTime().
{
             long sec = seconds + ttime.getSeconds();
             long usec = micro_seconds + ttime.getMicroseconds();
             sec += usec/USEC_SECOND;
             usec = usec%USEC_SECOND;
             return TuioTime(sec,usec);
         };
operator-() [1/2]
TuioTime TUIO::TuioTime::operator- (long us) inline
Subtracts the provided time represented in Microseconds from the private Seconds and Microseconds attributes.
Parameters
us the total time to subtract in Microseconds
Returns
the subtraction result of this TuioTime minus the provided time in Microseconds
Definition at line 125 of file TuioTime.h.
References TuioTime().
{
             long sec = seconds - us/USEC_SECOND;
             long usec = micro_seconds - us%USEC_SECOND;
             if (usec<0) {
                 usec += USEC_SECOND;
                 sec--;
             }
             return TuioTime(sec,usec);
         };
operator-() [2/2]
TuioTime TUIO::TuioTime::operator- (TuioTime ttime) inline
Subtracts the provided TuioTime from the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to subtract
Returns
the subtraction result of this TuioTime minus the provided TuioTime
Definition at line 143 of file TuioTime.h.
References getMicroseconds(), getSeconds(), and TuioTime().
{
             long sec = seconds - ttime.getSeconds();
             long usec = micro_seconds - ttime.getMicroseconds();
             if (usec<0) {
                 usec += USEC_SECOND;
                 sec--;
             }
             return TuioTime(sec,usec);
         };
operator=()
void TUIO::TuioTime::operator= (TuioTime ttime) inline
Assigns the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to assign
Definition at line 161 of file TuioTime.h.
References getMicroseconds(), and getSeconds().
{
             seconds = ttime.getSeconds();
             micro_seconds = ttime.getMicroseconds();
         };
operator==()
bool TUIO::TuioTime::operator== (TuioTime ttime) inline
Takes a TuioTime argument and compares the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to compare
Returns
true if the two TuioTime have equal Seconds and Microseconds attributes
Definition at line 172 of file TuioTime.h.
References getMicroseconds(), and getSeconds().
{
             if ((seconds==(long)ttime.getSeconds()) && (micro_seconds==(long)ttime.getMicroseconds())) return true;
             else return false;
         };
reset()
void TUIO::TuioTime::reset () inline
Resets the seconds and micro_seconds attributes to zero.
Definition at line 191 of file TuioTime.h.
                      {
             seconds = 0;
             micro_seconds = 0;
         };
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Tuio_Client/TuioTime.h