Sabina: IPlugin Class Reference
IPlugin Class Reference abstract
#include <plugin.h>
Public Member Functions
virtual bool Initialize_Output ()=0
Initialize Output variables for the plugin to publish.
virtual bool Initialize_Input ()=0
Initialize Input variables for the plugin to publish.
virtual void Main ()=0
Main funcction of the plugin.
virtual bool loadConfiguration ()=0
Load configuration.
virtual bool saveConfiguration ()=0
Save configuration.
virtual void run ()=0
Execute plugin.
virtual void stop ()=0
Stop plugin.
Static Public Member Functions
static void * IncWrapper (void *thisPtr)
Wrapps the Main function of the plugin object to ANSI C to be pased as a parameter to pthread_create.
Public Attributes
pthread_t thread_id
bool running
bool stoped
Detailed Description
An abstract interface for plugins to create new plugins.
Definition at line 18 of file plugin.h.
Member Function Documentation
IncWrapper()
static void* IPlugin::IncWrapper (void * thisPtr) inline static
Wrapps the Main function of the plugin object to ANSI C to be pased as a parameter to pthread_create.
This process alows plugins to be running in a new thread each (don't change this unless you know what you are doing)
Returns
static void
Definition at line 94 of file plugin.h.
Referenced by Color_Tracker::run(), File_Writer::run(), Function_Caller::run(), Camera_Reader::run(), Joystick_Writer::run(), Network_Client::run(), Network_Server::run(), Screen_Reader::run(), and Tuio_Client::run().
     {
       ((IPlugin*) thisPtr)->Main();
       return NULL;
     }
Initialize_Input()
virtual bool IPlugin::Initialize_Input () pure virtual
Initialize Input variables for the plugin to publish.
Returns
bool
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Camera_Reader, Joystick_Writer, Function_Caller, Function_Test, Color_Tracker, and File_Writer.
Initialize_Output()
virtual bool IPlugin::Initialize_Output () pure virtual
Initialize Output variables for the plugin to publish.
Returns
bool
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Camera_Reader, Joystick_Writer, Function_Caller, Function_Test, Color_Tracker, and File_Writer.
Referenced by PluginManager::Initialize(), and PluginManager::InitializeAll().
loadConfiguration()
virtual bool IPlugin::loadConfiguration () pure virtual
Load configuration.
The configuration can be loaded from file, or be hard coded into the plugin (not recomended), initialization of public and private variables should occur here
By default loadConfiguration is called during PluginManager::Initialize() by the plugin manager.
Returns
bool
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Camera_Reader, Joystick_Writer, Function_Caller, Function_Test, Color_Tracker, and File_Writer.
Main()
virtual void IPlugin::Main () pure virtual
Main funcction of the plugin.
Started in a new thread by the Run() funcction is the most importatn funcction of the plugin. Infinite loop (generaly a while(running) function that runs undefenitly in a read/process/write cicle).
Returns
void
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Camera_Reader, Joystick_Writer, Function_Caller, Function_Test, Color_Tracker, and File_Writer.
run()
virtual void IPlugin::run () pure virtual
Execute plugin.
Starts a new thread and executes the plugins main() funcction.
Returns
void
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Joystick_Writer, Camera_Reader, Function_Caller, Function_Test, Color_Tracker, and File_Writer.
saveConfiguration()
virtual bool IPlugin::saveConfiguration () pure virtual
Save configuration.
The configuration should be saved to file, public and private variables that should be configured at startup should be saved.
By default saveConfiguration is called during PluginManager::Unload() by the plugin manager.
Returns
bool
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Camera_Reader, Joystick_Writer, Function_Caller, Function_Test, Color_Tracker, and File_Writer.
stop()
virtual void IPlugin::stop () pure virtual
Stop plugin.
Stops the plugin
Returns
void
Implemented in Tuio_Client, Screen_Reader, Network_Server, Network_Client, Joystick_Writer, Camera_Reader, File_Writer, Function_Caller, Function_Test, and Color_Tracker.
The documentation for this class was generated from the following file:
/home/patrick/projects/Gesture_Therapy_Linux/src/Plugin_API/plugin.h